# Generated by Django 5.0 on 2025-02-11 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_document_options_alter_page_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('icon', models.CharField(max_length=100)),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='website.publication')),
            ],
        ),
    ]
