# Generated by Django 5.0 on 2025-02-12 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_document_file_alter_issue_cover_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BackgroundImages',
            new_name='BackgroundImage',
        ),
    ]
