# Generated by Django 5.0 on 2025-02-12 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_rename_backgroundimages_backgroundimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='organization',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
