# Generated by Django 5.1.6 on 2025-02-12 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_publication_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageAllowedDocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('RULE', 'Rule'), ('TEMPLATE', 'Template'), ('ISSUE', 'Issue'), ('INFORMATION', 'Information'), ('OTHER', 'Other')], max_length=11)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='website.page')),
            ],
        ),
    ]
