# Generated by Django 5.1.6 on 2025-02-13 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_pagealloweddocumenttype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='document',
            new_name='file',
        ),
    ]
