# Generated by Django 5.1.6 on 2025-02-13 03:43

import django_summernote.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_rename_document_issue_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('RULE', 'Rule'), ('TEMPLATE', 'Template'), ('INFORMATION', 'Information'), ('OTHER', 'Other')], max_length=11),
        ),
        migrations.AlterField(
            model_name='issue',
            name='presentation',
            field=django_summernote.fields.SummernoteTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='pagealloweddocumenttype',
            name='document_type',
            field=models.CharField(choices=[('RULE', 'Rule'), ('TEMPLATE', 'Template'), ('INFORMATION', 'Information'), ('OTHER', 'Other')], max_length=11),
        ),
        migrations.AlterField(
            model_name='publication',
            name='description',
            field=django_summernote.fields.SummernoteTextField(),
        ),
        migrations.AlterField(
            model_name='text',
            name='text',
            field=django_summernote.fields.SummernoteTextField(),
        ),
    ]
