# Generated by Django 5.1.6 on 2025-02-14 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_alter_document_document_type_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PageAllowedDocumentType',
            new_name='PageAllowedDocumentCategory',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='document_type',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='pagealloweddocumentcategory',
            old_name='document_type',
            new_name='category',
        ),
    ]
