# Generated by Django 5.1.6 on 2025-02-14 16:45

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_rename_pagealloweddocumenttype_pagealloweddocumentcategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='', editable=False, populate_from=models.CharField(max_length=20), unique=True),
        ),
    ]
