# Generated by Django 5.1.6 on 2026-02-02 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='number',
            field=models.CharField(blank=True, max_length=10, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='issue',
            name='volume',
            field=models.CharField(blank=True, max_length=10, verbose_name='Volume'),
        ),
    ]
