# Generated by Django 5.1.6 on 2026-04-16 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_issue_number_issue_volume'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='link_address',
            field=models.URLField(blank=True, verbose_name='Endereço do link'),
        ),
        migrations.AlterField(
            model_name='page',
            name='page_type',
            field=models.CharField(choices=[('DL', 'Downloads'), ('TX', 'Texto'), ('IS', 'Edições'), ('LK', 'Link')], max_length=2, verbose_name='Tipo de página'),
        ),
    ]
