# Generated by Django 5.1.6 on 2026-04-16 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_page_link_address_alter_page_page_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='page_type',
            field=models.CharField(choices=[('DL', 'Downloads'), ('TX', 'Texto'), ('IS', 'Edições'), ('LK', 'Link'), ('CI', 'Edição Atual')], max_length=2, verbose_name='Tipo de página'),
        ),
    ]
