# Generated by Django 5.1.6 on 2026-04-16 17:43

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_alter_page_page_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, default='', editable=False, populate_from='title', unique=True),
        ),
    ]
