# Generated by Django 5.1.6 on 2025-04-04 13:14

import autoslug.fields
import django.core.validators
import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Título')),
                ('order', models.IntegerField(verbose_name='Ordem')),
                ('page_type', models.CharField(choices=[('DL', 'Downloads'), ('GL', 'Galeria'), ('TX', 'Texto'), ('IS', 'Edições')], max_length=2, verbose_name='Tipo de página')),
                ('slug', autoslug.fields.AutoSlugField(default='', editable=False, populate_from='title', unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última modificação')),
                ('is_published', models.BooleanField(verbose_name='Publicado?')),
            ],
            options={
                'verbose_name': 'Página',
                'verbose_name_plural': 'Páginas',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('short_title', models.CharField(max_length=40, verbose_name='Título curto')),
                ('logo', models.ImageField(blank=True, upload_to='publication/', verbose_name='Logo')),
                ('logo_mini', models.ImageField(blank=True, upload_to='publication/', verbose_name='Mini-logo')),
                ('promo_image', models.ImageField(blank=True, upload_to='publication/', verbose_name='Imagem promocional')),
                ('issn', models.CharField(blank=True, max_length=50, verbose_name='ISSN')),
                ('doi', models.CharField(blank=True, max_length=50, verbose_name='DOI')),
                ('organization', models.CharField(blank=True, max_length=100, verbose_name='Instituição')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='Endereço')),
                ('phone', models.CharField(blank=True, max_length=100, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('description', tinymce.models.HTMLField(verbose_name='Descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
            ],
            options={
                'verbose_name': 'Publicação',
                'verbose_name_plural': 'Publicações',
            },
        ),
        migrations.CreateModel(
            name='PageAllowedDocumentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('RULE', 'Norma'), ('TEMPLATE', 'Template'), ('INFORMATION', 'Informação'), ('OTHER', 'Outro')], max_length=11, verbose_name='Categoria')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.page', verbose_name='Página')),
            ],
            options={
                'verbose_name': 'Categoria de documento permitida',
                'verbose_name_plural': 'Categorias de documento permitidas',
            },
        ),
        migrations.AddField(
            model_name='page',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.publication', verbose_name='Publicação'),
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, null=True, verbose_name='Título')),
                ('presentation', tinymce.models.HTMLField(blank=True, verbose_name='Apresentação')),
                ('cover', models.ImageField(blank=True, upload_to='issue/', verbose_name='Capa')),
                ('file', models.FileField(blank=True, upload_to='issue/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'PDF'])], verbose_name='Arquivo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última modificação')),
                ('pub_date', models.DateField(verbose_name='Data de publicação')),
                ('url', models.URLField(blank=True, verbose_name='URL')),
                ('is_published', models.BooleanField(default=False, verbose_name='Publicado?')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.publication', verbose_name='Publicação')),
            ],
            options={
                'verbose_name': 'Edição',
                'verbose_name_plural': 'Edições',
                'ordering': ['-pub_date'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('category', models.CharField(choices=[('RULE', 'Norma'), ('TEMPLATE', 'Template'), ('INFORMATION', 'Informação'), ('OTHER', 'Outro')], max_length=11, verbose_name='Categoria')),
                ('file', models.FileField(upload_to='documents/', verbose_name='Arquivo')),
                ('is_published', models.BooleanField(verbose_name='Publicado?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última modificação')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.publication', verbose_name='Publicação')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='BackgroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(verbose_name='Ordem')),
                ('image', models.ImageField(upload_to='background/', verbose_name='Imagem')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.publication', verbose_name='Publicação')),
            ],
            options={
                'verbose_name': 'Imagem de fundo',
                'verbose_name_plural': 'Imagens de fundo',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='URL')),
                ('icon', models.CharField(max_length=100, verbose_name='Ícone')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.publication', verbose_name='Publicação')),
            ],
            options={
                'verbose_name': 'Mídia Social',
                'verbose_name_plural': 'Mídias Sociais',
            },
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Título')),
                ('subtitle', models.CharField(blank=True, max_length=100, verbose_name='Subtítulo')),
                ('order', models.IntegerField(verbose_name='Ordem')),
                ('text', tinymce.models.HTMLField(verbose_name='Texto')),
                ('is_published', models.BooleanField(verbose_name='Publicado?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última modificação')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.page', verbose_name='Página')),
            ],
            options={
                'verbose_name': 'Texto',
                'verbose_name_plural': 'Textos',
                'ordering': ['order'],
            },
        ),
    ]
