# Generated by Django 5.1.6 on 2025-04-04 17:38

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='text',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Texto'),
        ),
        migrations.AlterField(
            model_name='page',
            name='page_type',
            field=models.CharField(choices=[('DL', 'Downloads'), ('TX', 'Texto'), ('IS', 'Edições')], max_length=2, verbose_name='Tipo de página'),
        ),
        migrations.DeleteModel(
            name='Text',
        ),
    ]
