# Generated by Django 5.1.6 on 2025-04-06 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_page_text_alter_page_page_type_delete_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='banner_image',
            field=models.ImageField(blank=True, upload_to='publication/', verbose_name='Imagem do Banner'),
        ),
    ]
