# Generated by Django 5.1.6 on 2025-03-16 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='is_published',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='page',
            name='is_published',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
