# Generated by Django 5.1.6 on 2025-03-27 02:05

import django.core.validators
import django.db.models.deletion
import django_summernote.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_issue_is_published_page_is_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='backgroundimage',
            options={'ordering': ['order'], 'verbose_name': 'Imagem de fundo', 'verbose_name_plural': 'Imagens de fundo'},
        ),
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['title'], 'verbose_name': 'Documento', 'verbose_name_plural': 'Documentos'},
        ),
        migrations.AlterModelOptions(
            name='issue',
            options={'ordering': ['-pub_date'], 'verbose_name': 'Edição', 'verbose_name_plural': 'Edições'},
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['order'], 'verbose_name': 'Página', 'verbose_name_plural': 'Páginas'},
        ),
        migrations.AlterModelOptions(
            name='pagealloweddocumentcategory',
            options={'verbose_name': 'Categoria de documento permitida', 'verbose_name_plural': 'Categorias de documento permitidas'},
        ),
        migrations.AlterModelOptions(
            name='publication',
            options={'verbose_name': 'Publicação', 'verbose_name_plural': 'Publicações'},
        ),
        migrations.AlterModelOptions(
            name='socialmedia',
            options={'verbose_name': 'Mídia Social', 'verbose_name_plural': 'Mídias Sociais'},
        ),
        migrations.AlterModelOptions(
            name='text',
            options={'ordering': ['order'], 'verbose_name': 'Texto', 'verbose_name_plural': 'Textos'},
        ),
        migrations.AlterField(
            model_name='backgroundimage',
            name='image',
            field=models.ImageField(upload_to='background/', verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='backgroundimage',
            name='order',
            field=models.IntegerField(verbose_name='Ordem'),
        ),
        migrations.AlterField(
            model_name='backgroundimage',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.publication', verbose_name='Publicação'),
        ),
        migrations.AlterField(
            model_name='document',
            name='category',
            field=models.CharField(choices=[('RULE', 'Norma'), ('TEMPLATE', 'Template'), ('INFORMATION', 'Informação'), ('OTHER', 'Outro')], max_length=11, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='document',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de criação'),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='documents/', verbose_name='Arquivo'),
        ),
        migrations.AlterField(
            model_name='document',
            name='is_published',
            field=models.BooleanField(verbose_name='Publicado?'),
        ),
        migrations.AlterField(
            model_name='document',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.publication', verbose_name='Publicação'),
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='document',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Última modificação'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='cover',
            field=models.ImageField(blank=True, upload_to='issue/', verbose_name='Capa'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de criação'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='file',
            field=models.FileField(blank=True, upload_to='issue/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'PDF'])], verbose_name='Arquivo'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Publicado?'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='presentation',
            field=django_summernote.fields.SummernoteTextField(blank=True, verbose_name='Apresentação'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='pub_date',
            field=models.DateField(verbose_name='Data de publicação'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.publication', verbose_name='Publicação'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='title',
            field=models.CharField(max_length=20, null=True, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Última modificação'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='url',
            field=models.URLField(blank=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='page',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de criação'),
        ),
        migrations.AlterField(
            model_name='page',
            name='is_published',
            field=models.BooleanField(verbose_name='Publicado?'),
        ),
        migrations.AlterField(
            model_name='page',
            name='order',
            field=models.IntegerField(verbose_name='Ordem'),
        ),
        migrations.AlterField(
            model_name='page',
            name='page_type',
            field=models.CharField(choices=[('DL', 'Downloads'), ('GL', 'Galeria'), ('TX', 'Texto'), ('IS', 'Edições')], max_length=2, verbose_name='Tipo de página'),
        ),
        migrations.AlterField(
            model_name='page',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.publication', verbose_name='Publicação'),
        ),
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(max_length=20, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='page',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Última modificação'),
        ),
        migrations.AlterField(
            model_name='pagealloweddocumentcategory',
            name='category',
            field=models.CharField(choices=[('RULE', 'Norma'), ('TEMPLATE', 'Template'), ('INFORMATION', 'Informação'), ('OTHER', 'Outro')], max_length=11, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='pagealloweddocumentcategory',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.page', verbose_name='Página'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='address',
            field=models.CharField(blank=True, max_length=200, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de criação'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='description',
            field=django_summernote.fields.SummernoteTextField(verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='doi',
            field=models.CharField(blank=True, max_length=50, verbose_name='DOI'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='issn',
            field=models.CharField(blank=True, max_length=50, verbose_name='ISSN'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='logo',
            field=models.ImageField(blank=True, upload_to='publication/', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='logo_mini',
            field=models.ImageField(blank=True, upload_to='publication/', verbose_name='Mini-logo'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='organization',
            field=models.CharField(blank=True, max_length=100, verbose_name='Instituição'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='phone',
            field=models.CharField(blank=True, max_length=100, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='promo_image',
            field=models.ImageField(blank=True, upload_to='publication/', verbose_name='Imagem promocional'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='short_title',
            field=models.CharField(max_length=40, verbose_name='Título curto'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Data de atualização'),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='icon',
            field=models.CharField(max_length=100, verbose_name='Ícone'),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.publication', verbose_name='Publicação'),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='url',
            field=models.URLField(verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='text',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de criação'),
        ),
        migrations.AlterField(
            model_name='text',
            name='is_published',
            field=models.BooleanField(verbose_name='Publicado?'),
        ),
        migrations.AlterField(
            model_name='text',
            name='order',
            field=models.IntegerField(verbose_name='Ordem'),
        ),
        migrations.AlterField(
            model_name='text',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.page', verbose_name='Página'),
        ),
        migrations.AlterField(
            model_name='text',
            name='subtitle',
            field=models.CharField(blank=True, max_length=100, verbose_name='Subtítulo'),
        ),
        migrations.AlterField(
            model_name='text',
            name='text',
            field=django_summernote.fields.SummernoteTextField(verbose_name='Texto'),
        ),
        migrations.AlterField(
            model_name='text',
            name='title',
            field=models.CharField(blank=True, max_length=100, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='text',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Última modificação'),
        ),
    ]
