# Generated by Django 5.1.6 on 2025-04-06 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_publication_banner_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BackgroundImage',
        ),
    ]
