# Generated by Django 5.0 on 2023-12-29 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_anais_anal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Areas',
            fields=[
                ('nome', models.CharField(max_length=60, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'verbose_name': 'Área',
                'verbose_name_plural': 'Áreas',
            },
        ),
        migrations.CreateModel(
            name='Artigos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('equipe', models.CharField(max_length=255)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.areas')),
            ],
            options={
                'verbose_name': 'Artigo',
                'verbose_name_plural': 'Anais',
            },
        ),
        migrations.CreateModel(
            name='Normas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('norma', models.CharField(max_length=20, null=True)),
                ('arquivo', models.FileField(upload_to='')),
            ],
            options={
                'verbose_name': 'Norma',
                'verbose_name_plural': 'Normas',
            },
        ),
        migrations.CreateModel(
            name='Textos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20, null=True)),
                ('titulo', models.CharField(max_length=20)),
                ('subtitulo', models.CharField(max_length=100)),
                ('texto', models.TextField()),
            ],
            options={
                'verbose_name': 'Texto',
                'verbose_name_plural': 'Textos',
            },
        ),
        migrations.DeleteModel(
            name='Anal',
        ),
        migrations.DeleteModel(
            name='HTMLText',
        ),
    ]
