# Generated by Django 5.1.6 on 2025-04-03 18:16

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_backgroundimage_options_alter_document_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='presentation',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Apresentação'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='description',
            field=tinymce.models.HTMLField(verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='text',
            name='text',
            field=tinymce.models.HTMLField(verbose_name='Texto'),
        ),
    ]
