# Generated by Django 5.0 on 2024-02-23 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_comissao_edicoes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textos',
            name='nome',
        ),
    ]
