# Generated by Django 5.0 on 2023-12-23 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_anais'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Anais',
            new_name='Anal',
        ),
    ]
